name: deploy-gh-pages
on: 
  push:
    branches:
      - main
      - dev
jobs:
  deployment:
    name: GH Pages deploy
    runs-on: ubuntu-latest
    steps:
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1  

      - name: Set user for the Action
        run: 

      - name: Install Dependencies
        run: |
          npm i
      
      - name: Build and deploy
        run: |
          npm run deploy
